{% set version = "1.3.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ddalpha
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ddalpha_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ddalpha/ddalpha_{{ version }}.tar.gz
  sha256: e4a60a4e0950a3587db2a2d5958ab4fbe07b2548f7c3d4795912fe45c77a4eae

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-geometry
    - r-robustbase
    - r-sfsmisc
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    # BH is the header-only part of Boost and thus a compile-time requirement only
    # - r-bh
    - r-mass
    - r-rcpp >=0.11.0
    - r-class
    - r-geometry
    - r-robustbase
    - r-sfsmisc

test:
  commands:
    - $R -e "library('ddalpha')"           # [not win]
    - "\"%R%\" -e \"library('ddalpha')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ddalpha
  license: GPL-2.0-only
  summary: Contains procedures for depth-based supervised learning, which are entirely non-parametric, in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014 <doi:10.1007/s00362-012-0488-4>). The training data sample is transformed by a statistical depth function to a compact low-dimensional space, where
    the final classification is done. It also offers an extension to functional data and routines for calculating certain notions of statistical depth functions. 50 multivariate and 5 functional classification problems are included.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ddalpha
# Type: Package
# Title: Depth-Based Classification and Calculation of Data Depth
# Version: 1.3.8
# Date: 2019-01-06
# Authors@R: c(person("Oleksii", "Pokotylo", role=c("aut", "cre"), email = "alexey.pokotylo@gmail.com"), person("Pavlo", "Mozharovskyi", role=c("aut"), email = "pavlo.mozharovskyi@ensai.fr"), person("Rainer", "Dyckerhoff", role=c("aut"), email = "rainer.dyckerhoff@statistik.uni-koeln.de"), person("Stanislav", "Nagy", role=c("aut"), email = "nagy@karlin.mff.cuni.cz"))
# SystemRequirements: C++11
# Depends: R (>= 2.10), stats, utils, graphics, grDevices, MASS, class, robustbase, sfsmisc, geometry
# Imports: Rcpp (>= 0.11.0)
# LinkingTo: BH, Rcpp
# Description: Contains procedures for depth-based supervised learning, which are entirely non-parametric, in particular the DDalpha-procedure (Lange, Mosler and Mozharovskyi, 2014 <doi:10.1007/s00362-012-0488-4>). The training data sample is transformed by a statistical depth function to a compact low-dimensional space, where the final classification is done. It also offers an extension to functional data and routines for calculating certain notions of statistical depth functions. 50 multivariate and 5 functional classification problems are included.
# License: GPL-2
# NeedsCompilation: yes
# Packaged: 2019-01-06 14:13:33 UTC; User
# Author: Oleksii Pokotylo [aut, cre], Pavlo Mozharovskyi [aut], Rainer Dyckerhoff [aut], Stanislav Nagy [aut]
# Maintainer: Oleksii Pokotylo <alexey.pokotylo@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-06 15:40:03 UTC
