# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FhKp2FnV1OkfHV8FbemjwwNW4FVwdew1lsK7ojgTyMF/G8CVTrTxZGDlpHi+AdF/J8ZSbrkLnnkh7SJ/v7SxDCJ6j1Qu2kGRfmRCRMwe89tsJtZZPKRIjTozMT4+5egYSK4sEx4ASXpQLg6oe5CrysPKyCnXSn3+DakvTbFh4YDTi+1tjwj5XW5C6Jp62C3KRXRMFIRDse4egqUEYa3Cj8EU6fZjHd93ZpxkQ5WV+Ga3/QnXw/lGng9MIxJC7XChTjWVjphUKgYdKvoQ06/r/TxCAfv+yWtBHTDW/hEq3OqcuY/WiomJUZkUNltCcuVmzZ3gtf/MynkELSoCpc01LrfxkfSlQfV6Ba01pGxaZrRv2ZmAYbAvh5UXpX4ILvpBKNWcdMrl3HAYnfmDq8OQ5N/5vnRESHxsxOShGq6Shs38rxMnmbXyqtyM2qSP8YTAfZlDRgnt1P7oXmtE4fMizvbFd4y8xes9oaxKZPomaa5uGV0AHIoAa1ckF2oiW2NZWLrQLjSHVA0dfWt9OROWKwOBxWWwOjUxD3KH256GZzwbsZ7EIC+WKWaKrccgyL5A8VRIjxtEJDMzpsETOtx7Ci8Al5QK/pVNHi4v9O640UxJtd2/0J+fBOYucGX0IPA6WccbUe59/emkPzMLzWuTUzBwflLk/MDZhe9llF+e8lo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
