# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FhKp2FnV1OkfHV8FbemjwwNW4FVwdew1lsK7ojgTyMF/G8CVTrTxZGDlpHi+AdF/J8ZSbrkLnnkh7SJ/v7SxDCJ6j1Qu2kGRfmRCRMwe89tsJtZZPKRIjTozMT4+5egYSK4sEx4ASXpQLg6oe5CrysPKyCnXSn3+DakvTbFh4YDTi+1tjwj5XW5C6Jp62C3KRXRMFIRDse4egqUEYa3Cj8EU6fZjHd93ZpxkQ5WV+Ga3/QnXw/lGng9MIxJC7XChTjWVjphUKgYdKvoQ06/r/TxCAfv+yWtBHTDW/hEq3OqcuY/WiomJUZkUNltCcuVmzZ3gtf/MynkELSoCpc01LrfxkfSlQfV6Ba01pGxaZrRv2ZmAYbAvh5UXpX4ILvpBKNWcdMrl3HAYnfmDq8OQ5N/5vnRESHxsxOShGq6Shs38rxMnmbXyqtyM2qSP8YTAfZlDRgnt1P7oXmtE4fMizvbFd4y8xes9oaxKZPomaa5uGV0AHIoAa1ckF2oiW2NZWLrQLjSHVA0dfWt9OROWKwOBxWWwOjUxD3KH256GZzwbsZ7EIC+WKWaKrccgyL5A8VRIjxtEJDMzpsETOtx7Ci8Al5QK/pVNHi4v9O640UxJtd2/0J+fBOYucGX0IPA6WccbUe59/emkPzMLzWuTUzBwflLk/MDZhe9llF+e8lo="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi