appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FhKp2FnV1OkfHV8FbemjwwNW4FVwdew1lsK7ojgTyMF/G8CVTrTxZGDlpHi+AdF/J8ZSbrkLnnkh7SJ/v7SxDCJ6j1Qu2kGRfmRCRMwe89tsJtZZPKRIjTozMT4+5egYSK4sEx4ASXpQLg6oe5CrysPKyCnXSn3+DakvTbFh4YDTi+1tjwj5XW5C6Jp62C3KRXRMFIRDse4egqUEYa3Cj8EU6fZjHd93ZpxkQ5WV+Ga3/QnXw/lGng9MIxJC7XChTjWVjphUKgYdKvoQ06/r/TxCAfv+yWtBHTDW/hEq3OqcuY/WiomJUZkUNltCcuVmzZ3gtf/MynkELSoCpc01LrfxkfSlQfV6Ba01pGxaZrRv2ZmAYbAvh5UXpX4ILvpBKNWcdMrl3HAYnfmDq8OQ5N/5vnRESHxsxOShGq6Shs38rxMnmbXyqtyM2qSP8YTAfZlDRgnt1P7oXmtE4fMizvbFd4y8xes9oaxKZPomaa5uGV0AHIoAa1ckF2oiW2NZWLrQLjSHVA0dfWt9OROWKwOBxWWwOjUxD3KH256GZzwbsZ7EIC+WKWaKrccgyL5A8VRIjxtEJDMzpsETOtx7Ci8Al5QK/pVNHi4v9O640UxJtd2/0J+fBOYucGX0IPA6WccbUe59/emkPzMLzWuTUzBwflLk/MDZhe9llF+e8lo=
